"""Step 4 — assemble (qualified leads only).

Generate a research brief (company summary + openings by function + momentum +
qualification rationale + 2–3 outreach hooks) and a personalised AIDA cold email
with an open-optimised subject line.
"""

from __future__ import annotations

from anthropic import Anthropic

from .company_research import _extract_json, response_text
from .config import Settings, load_prompt
from .models import Brief, CompanySummary, HiringSignals, QualResult
from .qualify import _render_hiring, _render_summary
from .utils.cache import Cache, make_key
from .utils.logger import get_logger

log = get_logger("assemble")


class Assembler:
    def __init__(self, settings: Settings, client: Anthropic, offer_text: str, cache: Cache | None = None):
        self.settings = settings
        self.client = client
        self.offer_text = offer_text
        self.cache = cache
        self.content_prompt = load_prompt("brief")

    def assemble(
        self,
        summary: CompanySummary,
        hiring: HiringSignals,
        qual: QualResult,
        company_name: str | None,
    ) -> Brief:
        domain = summary.domain
        cache_key = make_key("brief", domain, self.settings.model, self.offer_text, qual.score)
        if self.cache:
            cached = self.cache.get("brief", cache_key)
            if cached:
                log.info(f"[{domain}] brief from cache")
                return Brief(**cached)

        prompt = self.content_prompt.format(
            offer=self.offer_text,
            company_name=company_name or domain,
            domain=domain,
            company_summary=_render_summary(summary),
            hiring_signals=_render_hiring(hiring),
            score=qual.score,
            rationale=qual.rationale,
        )
        try:
            resp = self.client.messages.create(
                model=self.settings.model,
                max_tokens=4000,
                messages=[{"role": "user", "content": prompt}],
            )
            data = _extract_json(response_text(resp))
        except Exception as e:  # noqa: BLE001
            log.warning(f"[{domain}] assembly failed: {e}")
            return Brief(domain=domain, error=f"assembly failed: {e}")

        brief = Brief(
            domain=domain,
            outreach_hooks=data.get("outreach_hooks", []) or [],
            email_subject=data.get("email_subject", "").strip(),
            email_body=data.get("email_body", "").strip(),
            markdown=self._render_markdown(
                company_name or domain, domain, summary, hiring, qual, data
            ),
        )
        if self.cache:
            from dataclasses import asdict
            self.cache.set("brief", cache_key, asdict(brief))
        return brief

    def _render_markdown(self, name, domain, summary, hiring, qual, data) -> str:
        """Assemble the brief from structured parts — stable section headers."""
        hooks = data.get("outreach_hooks", []) or []
        functions = ", ".join(f"{fn} ({n})" for fn, n in hiring.by_function.items()) or "—"

        roles_block = ""
        if hiring.openings:
            by_fn: dict[str, list] = {}
            for o in hiring.openings:
                by_fn.setdefault(o.function, []).append(o)
            for fn, roles in sorted(by_fn.items(), key=lambda kv: -len(kv[1])):
                roles_block += f"\n**{fn}** ({len(roles)})\n"
                for r in roles[:12]:
                    loc = f" — {r.location}" if r.location else ""
                    sen = f" · {r.seniority}" if r.seniority else ""
                    roles_block += f"- {r.title}{sen}{loc}\n"
        else:
            roles_block = "\n_No individual roles captured._\n"

        hooks_block = "\n".join(f"{i+1}. {h}" for i, h in enumerate(hooks)) or "_None_"

        return f"""# Research Brief — {name}

**Domain:** [{domain}](https://{domain})
**Fit score:** {qual.score}/10 — **QUALIFIED**
**Industry:** {summary.industry or "—"}
**ATS:** {hiring.ats or "—"} · **Careers:** {hiring.careers_url or "—"}

## Company Summary
{summary.summary or "_Not available._"}

**Products / Services:** {", ".join(summary.products_services) if summary.products_services else "—"}
**Size / Stage signals:** {summary.size_stage_signals or "—"}

## Currently Hiring ({hiring.total_open} open)
Functions actively hiring: {functions}
{roles_block}
## Hiring Momentum
{hiring.history_summary or "—"} _(trend: {hiring.trend})_

## Why They Qualify
{qual.rationale or "—"}

## Outreach Hooks
{hooks_block}

## Suggested Cold Email
**Subject:** {data.get("email_subject", "—")}

{data.get("email_body", "—")}

---
_Generated by Lead Qualifier. Offer context supplied by user._
"""
